version: '3.8'

services:
  app:
    build: .
    ports:
      - "4173:4173"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    command: yarn preview --host 0.0.0.0
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
